import 'package:hive/hive.dart';

import '../../features/editor/models/project.dart';
import '../../features/learn/models/lesson.dart';
import '../../features/learn/models/progress.dart';
import '../../features/quiz/models/question.dart';
import '../../features/quiz/models/quiz_attempt.dart';
import '../../features/quiz/models/unlock_timer.dart';

/// Registers all Hive adapters. Call once during app init, BEFORE opening boxes.
///
/// NOTE: The `*Adapter` classes referenced below are generated by hive_generator.
/// Run this BEFORE the first build:
///
///     flutter pub run build_runner build --delete-conflicting-outputs
void registerHiveAdapters() {
  if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(LessonAdapter());
  if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(ProgressAdapter());
  if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(ProjectAdapter());
  if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(QuestionAdapter());
  if (!Hive.isAdapterRegistered(4)) Hive.registerAdapter(QuizAttemptAdapter());
  if (!Hive.isAdapterRegistered(5)) Hive.registerAdapter(UnlockTimerAdapter());
}
